version: 0.0
os: linux
files:
  - source: target/myapp.jar
    destination: /var/www/inventory-test
hooks:
  AfterInstall:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root
